### ISSUE TITLE
Data packet format received from BTLE in Linux using Insight

### ISSUE THREAD

**Issue by YikeStone** [CymatiCorp/CyKITv2#12]
As mentioned here https://github.com/CymatiCorp/CyKITv2/blob/gitImages/Documentation/Bluetooth_Development-Epoc.pdf the data packet size is 19.
When I am capturing data packets using BTLE on Ubuntu 16.04.3, the size is 20.
Can anyone please tell me the data format or how to get data from these packets.
I have attached raw data capture from BTLE.
[insight_raw_data.log](https://github.com/CymatiCorp/CyKITv2/files/1845420/insight_raw_data.log)

**Comment by YikeStone** [comment]
The Header and Footer part of data packet is also not according to what is mentioned in the link.
The last byte seems to be the counter that is mentioned as the first byte in the link.

**Comment by YikeStone** [comment]
Pls help me with this problem. I want to know the decryption key for BTLE as well.

**Comment by Sebbyastian** [comment]
Hi. I searched for the term "19" within the PDF and found this quote:

> The following will strip away bytes 00 and 01 as well as 18 and 19 leaving us with the 16 bytes of headset data for decryption.

Is this what you were referring to when you say the packet size is 19? The header for the first packet is at byte 00, and the footer starts at byte 17 and continues for two bytes, meaning the half-packets from the stream are actually 20 bytes each, and a full packet is 40 bytes.

To be clear on zero-based indexing: When you have an array containing 1 element, that element is at `array[0]`. In an array containing two elements you have `array[0]` and `array[1]` but not `array[2]` (that would need an array of three elements). In an array containing twenty elements, you have `array[0]` up to `array[19]` but not `array[20]` (you would need an array of 21 elements for `array[20]`).

I have run your log file through a simple program to count multiples of twenty, and it all seems to divide evenly to me. I think I've explained away the misconceptions you had about packet size versus byte index within packets, so that you should understand yourself. Feel free to review my program and play around for yourself...

![image](https://user-images.githubusercontent.com/5820558/41321864-3f1daef8-6ee9-11e8-9424-1061fe3d1845.png)

    #include <stdio.h>
    #include <stddef.h>
    
    int main(void) {
    	size_t counter = 0;
    	while (scanf("0x%*02X ") == 0) // as opposed to EOF
    		counter++;
    	printf("Total of %zu packets received with %zu bytes remaining.", counter / 20, counter % 20);
    	return 0;
    }

Just be sure to remember an array containing 20 elements has indexes 0 through to 19; index 20 is not valid in such an array.

**Comment by YikeStone** [comment]
Hey @Sebbyastian. Thanks for your reply and efforts. I should have closed this issue but forgot that I had opened it. I know about how array indexing work. There is a typo in the PDF, I had realised it later, there is an example in the PDF and that example has 19 bytes instead of 20. So, that got me confused.

All thanks to @warrenarea, I have solved all my problems. He helped me with decryption.
