### ISSUE TITLE
Is the raw data obtained from Cykitv2 same as from emotivPro?

### ISSUE THREAD

**Issue by imyzx2017** [CymatiCorp/CyKITv2#14]
Hi warrenarea,

I have used your project, it's an excellent project, I can get EEG raw data to do some experiments.
But I have a question: is the raw data obtained from Cykitv2 same as from EmotivPro? 
Thanks a lot!!

**Comment by warrenarea** [comment]
the data from EmotivPRO and EDK, all do conversions to acquire a value that is a measurement
for the microvoltage.  where its average floats around 4201 microvolts.  

The conversion done from CyKITv2, is a very close approximation to the one done by EmotivPRO,
the floating point numbers don't quite match up, but should be a close enough approximation.

Since each floating point value is relative to one another, the difference from EmotivPRO and CyKIT
would be negligible.  On the discord server, you may note there are several images showing the 
CyKITv2 rendering, matching up precisely to the Emotiv program renderings.... as well as the CSV
recordings, also matching up precisely.  EmotivPRO and CyKIT don't match precisely, but because
the values are relative to one another, it still is able to render the exact same... 

So in conclusion, the microvoltage floating point math will be slightly off, but it shouldn't be a problem
to anyones project, particularly because we tend not to be utilizing the microvoltage value itself, but
the difference between these values from one another.  For all intents and purposes, the values could
be in a completely different range... and still be rendered the exact same.  

Plus any variance in the microvoltage, is going to be off by a very small number, like .001242194
Which probably shouldn't make much of a difference.... especially considering that.... there are differences
in the microvoltage values from their EDK version and the EmotivPRO version, so what we're looking
at from the Emotiv products, are likely also... a close approximation. 

I hope this answers your question(s).

**Comment by imyzx2017** [comment]
I think it solved my question.So I can use the converted data to synthesis some signals like ERPs and continue my work. 

Thanks for your comments!! :smile:
